[build]
functions = "netlify/functions"
publish = "out"
command = "npm install && npm run build"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"